/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fabrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fabrics */
        get: operations["list_fabrics_api_v1_fabrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/counters/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Errors
         * @description Per-port error deltas over `(since, until]`, sparse.
         *
         *     A port is present only if a counter moved or a flag is raised; everything
         *     absent was measured, is zero, and is trusted. `coverage` is what makes that
         *     safe to read -- check it before believing an empty `ports`.
         */
        get: operations["errors_api_v1_fabrics__fabric__counters_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/counters/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Traffic
         * @description Per-port transmit and receive rates over a trailing window, sparse.
         *
         *     A rate, not a delta: `at` names the instant to read *at*, and `window` only
         *     says how long an interval to average over. Ports below the idle floor are
         *     omitted; ports that could not be measured are present and flagged.
         */
        get: operations["traffic_api_v1_fabrics__fabric__counters_traffic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff
         * @description The union of both topologies, each element tagged with how it changed.
         */
        get: operations["diff_api_v1_fabrics__fabric__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Newest first. Defaults to the last 24 hours.
         *
         *     Complements the diff rather than duplicating it: a diff says a link is
         *     unchanged, this says it went down and came back forty times while nobody
         *     was looking.
         */
        get: operations["events_api_v1_fabrics__fabric__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Head
         * @description Cheap enough to poll. Refetch topology only when topology_hash moves.
         */
        get: operations["head_api_v1_fabrics__fabric__head_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Link
         * @description Both ends expanded in place, so selecting a link is one request.
         *
         *     The id is the canonical GUID-ordered form; the database's own port_id
         *     ordering never appears on the wire, so this parses without consulting it.
         */
        get: operations["link_api_v1_fabrics__fabric__links__link_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/nodes/{guid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node */
        get: operations["node_api_v1_fabrics__fabric__nodes__guid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshots
         * @description The collection-run index, newest first.
         *
         *     Every run writes a row whether or not anything changed, so this is what
         *     makes silence readable: a gap here is the collector being down, while a run
         *     of `changed = false` is a fabric that genuinely did not move. Those two must
         *     never render the same way, and only this endpoint can tell them apart.
         */
        get: operations["snapshots_api_v1_fabrics__fabric__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fabrics/{fabric}/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Topology
         * @description The graph as of `at`, or now.
         */
        get: operations["topology_api_v1_fabrics__fabric__topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CounterCoverage
         * @description How much of the fabric the window actually saw.
         *
         *     `unsupported` is fabric-level and per counter.
         */
        CounterCoverage: {
            /** Ports Expected */
            ports_expected: number;
            /** Ports Measured */
            ports_measured: number;
            /** Ports No Data */
            ports_no_data: number;
            /** Ports Partial */
            ports_partial: number;
            /** Ports Reset */
            ports_reset: number;
            /** Sweeps */
            sweeps: number;
            /** Unsupported */
            unsupported?: {
                [key: string]: number;
            };
        };
        /**
         * CounterWindow
         * @description Which readings actually bounded the delta.
         *
         *     Requested and observed instants are both present and they differ, because
         *     counters are sampled discretely: a request for 09:00 is answered by whatever
         *     reading sat nearest it. A client drawing a per-hour figure from a span that
         *     is not quite an hour is wrong, and without this cannot know it.
         */
        CounterWindow: {
            /** First At */
            first_at?: string | null;
            /** Last At */
            last_at?: string | null;
            /**
             * Requested Since
             * Format: date-time
             */
            requested_since: string;
            /**
             * Requested Until
             * Format: date-time
             */
            requested_until: string;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "raw" | "hourly";
            /** Span S */
            span_s?: number | null;
        };
        /** Counts */
        Counts: {
            /**
             * Cas
             * @default 0
             */
            cas: number;
            /** Health */
            health?: {
                [key: string]: number;
            };
            /**
             * Links
             * @default 0
             */
            links: number;
            /**
             * Nodes
             * @default 0
             */
            nodes: number;
            /**
             * Routers
             * @default 0
             */
            routers: number;
            /**
             * Switches
             * @default 0
             */
            switches: number;
        };
        /**
         * Diff
         * @description The union of both endpoints' topologies, annotated.
         *
         *     `churn` counts events regardless of net change, because a link that flapped
         *     repeatedly and came back is byte-identical in a net diff and is probably the
         *     most interesting thing in the range.
         *
         *     `system_groups` is the union of both endpoints', so a chassis that lost its
         *     last node is still there for the removed children to sit inside.
         */
        Diff: {
            /** Fabric */
            fabric: string;
            /** Links */
            links: components["schemas"]["DiffLink"][];
            /** Nodes */
            nodes: components["schemas"]["DiffNode"][];
            since: components["schemas"]["Resolved"];
            /** System Groups */
            system_groups?: {
                [key: string]: components["schemas"]["SystemGroup"];
            };
            /**
             * Unchanged Guaranteed
             * @default false
             */
            unchanged_guaranteed: boolean;
            until: components["schemas"]["Resolved"];
        };
        /** DiffLink */
        DiffLink: {
            after?: components["schemas"]["LinkElement"] | null;
            before?: components["schemas"]["LinkElement"] | null;
            /**
             * Change
             * @enum {string}
             */
            change: "added" | "removed" | "modified" | "unchanged";
            /**
             * Churn
             * @default 0
             */
            churn: number;
            /** Id */
            id: string;
        };
        /** DiffNode */
        DiffNode: {
            after?: components["schemas"]["NodeElement"] | null;
            before?: components["schemas"]["NodeElement"] | null;
            /**
             * Change
             * @enum {string}
             */
            change: "added" | "removed" | "modified" | "unchanged";
            /**
             * Churn
             * @default 0
             */
            churn: number;
            /** Id */
            id: string;
        };
        /** ErrorDeltas */
        ErrorDeltas: {
            /** Counters */
            counters: ("symbol_error" | "link_error_recovery" | "link_downed" | "rcv_errors" | "rcv_remote_phys_errors" | "rcv_switch_relay_errors" | "xmit_discards" | "xmit_constraint_errors" | "rcv_constraint_errors" | "local_link_integrity" | "excessive_buffer_overrun" | "vl15_dropped" | "xmit_wait" | "qp1_dropped")[];
            coverage: components["schemas"]["CounterCoverage"];
            /** Fabric */
            fabric: string;
            /** Ports */
            ports: components["schemas"]["PortErrorDelta"][];
            window: components["schemas"]["CounterWindow"];
        };
        /** Event */
        Event: {
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
            /** Event Id */
            event_id: number;
            /** Event Type */
            event_type: string;
            /** Link Id */
            link_id?: string | null;
            /** Node Guid */
            node_guid?: string | null;
            /** Node Label */
            node_label?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Peer Guid */
            peer_guid?: string | null;
            /** Peer Port Num */
            peer_port_num?: number | null;
            /** Port Num */
            port_num?: number | null;
            /** Snapshot Id */
            snapshot_id?: number | null;
        };
        /** Events */
        Events: {
            /** Events */
            events: components["schemas"]["Event"][];
            /** Fabric */
            fabric: string;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Until
             * Format: date-time
             */
            until: string;
        };
        /** FabricRow */
        FabricRow: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Fabric Id */
            fabric_id: number;
            /** Name */
            name: string;
            /** Subnet Prefix */
            subnet_prefix?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Head
         * @description Cheap poll target. Refetch topology only when topology_hash moves.
         */
        Head: {
            counts: components["schemas"]["Counts"];
            /** Fabric */
            fabric: string;
            resolved: components["schemas"]["Resolved"];
        };
        /** LinkDetail */
        LinkDetail: {
            a: components["schemas"]["LinkEnd"];
            b: components["schemas"]["LinkEnd"];
            /**
             * Health
             * @enum {string}
             */
            health: "ok" | "degraded" | "down" | "unknown";
            /** Id */
            id: string;
            /** Reason */
            reason?: string[];
            resolved: components["schemas"]["Resolved"];
        };
        /** LinkElement */
        LinkElement: {
            /**
             * Health
             * @enum {string}
             */
            health: "ok" | "degraded" | "down" | "unknown";
            /** Id */
            id: string;
            /** Rate Gbps */
            rate_gbps?: number | null;
            /** Source */
            source: string;
            /** Source Port */
            source_port: number;
            speed?: components["schemas"]["Rate"];
            /** Target */
            target: string;
            /** Target Port */
            target_port: number;
            width?: components["schemas"]["Rate"];
        };
        /** LinkEnd */
        LinkEnd: {
            /** Guid */
            guid: string;
            /** Label */
            label?: string | null;
            port: components["schemas"]["PortDetail"];
            /** Type */
            type?: ("ca" | "switch" | "router") | null;
        };
        /** NodeDetail */
        NodeDetail: {
            /** Desc */
            desc?: string | null;
            /** Device Id */
            device_id?: number | null;
            /** First Seen */
            first_seen?: string | null;
            /** Fw Version */
            fw_version?: string | null;
            /** Guid */
            guid: string;
            /**
             * Health
             * @enum {string}
             */
            health: "ok" | "degraded" | "down" | "unknown";
            /** Label */
            label: string;
            /** Model */
            model?: string | null;
            /** Num Ports */
            num_ports?: number | null;
            /** Ports */
            ports?: components["schemas"]["PortDetail"][];
            resolved: components["schemas"]["Resolved"];
            /** Sm State */
            sm_state?: string | null;
            /** System Image Guid */
            system_image_guid?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "ca" | "switch" | "router";
            /** Vendor */
            vendor?: string | null;
            /** Vendor Id */
            vendor_id?: number | null;
        };
        /** NodeElement */
        NodeElement: {
            /**
             * Health
             * @enum {string}
             */
            health: "ok" | "degraded" | "down" | "unknown";
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Num Ports */
            num_ports?: number | null;
            /** Sm Role */
            sm_role?: ("discovering" | "standby" | "master") | null;
            /** System Image Guid */
            system_image_guid?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "ca" | "switch" | "router";
        };
        /**
         * Peer
         * @description The far end of a port's link, resolved so a panel needs no second fetch.
         */
        Peer: {
            /** Guid */
            guid: string;
            /** Health */
            health?: ("ok" | "degraded" | "down" | "unknown") | null;
            /** Link Id */
            link_id: string;
            /** Name */
            name?: string | null;
            /** Port Num */
            port_num: number;
            /** Type */
            type?: ("ca" | "switch" | "router") | null;
        };
        /** PortDetail */
        PortDetail: {
            /** Cable */
            cable?: {
                [key: string]: unknown;
            } | null;
            /** Check Events */
            check_events?: string[];
            /** Counters */
            counters?: {
                [key: string]: number;
            } | null;
            /** Counters At */
            counters_at?: string | null;
            /** Counters Delta */
            counters_delta?: {
                [key: string]: number;
            } | null;
            /** Counters Span S */
            counters_span_s?: number | null;
            /** Lid */
            lid?: number | null;
            /** Mtu */
            mtu?: number | null;
            /** Mtu Bytes */
            mtu_bytes?: number | null;
            peer?: components["schemas"]["Peer"] | null;
            /** Phys State */
            phys_state?: string | null;
            /** Port Guid */
            port_guid?: string | null;
            /** Port Num */
            port_num: number;
            /** Rate Gbps */
            rate_gbps?: number | null;
            speed_active?: components["schemas"]["Rate"];
            speed_enabled?: components["schemas"]["Rate"];
            speed_supported?: components["schemas"]["Rate"];
            /** State */
            state?: string | null;
            traffic?: components["schemas"]["PortRate"] | null;
            width_active?: components["schemas"]["Rate"];
            width_enabled?: components["schemas"]["Rate"];
            width_supported?: components["schemas"]["Rate"];
        };
        /**
         * PortErrorDelta
         * @description One port's accumulation over the window.
         *
         *     Sparse in two directions: `d` carries only counters that moved, so a port
         *     with nothing to say is absent entirely.
         *
         *     Absence therefore means zero, which is only safe because every case where it
         *     would instead mean *unknown* raises a flag below.
         *
         *     Every field below `port` keeps a default and the route serialises with
         *     `exclude_defaults`, so a clean row is `{"node", "port", "d"}`.
         */
        PortErrorDelta: {
            /** D */
            d?: {
                [key: string]: number;
            };
            /**
             * No Data
             * @default false
             */
            no_data: boolean;
            /** Node */
            node: string;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /** Port */
            port: number;
            /**
             * Reset
             * @default false
             */
            reset: boolean;
            /** Unsupported */
            unsupported?: ("symbol_error" | "link_error_recovery" | "link_downed" | "rcv_errors" | "rcv_remote_phys_errors" | "rcv_switch_relay_errors" | "xmit_discards" | "xmit_constraint_errors" | "rcv_constraint_errors" | "local_link_integrity" | "excessive_buffer_overrun" | "vl15_dropped" | "xmit_wait" | "qp1_dropped")[];
        };
        /**
         * PortRate
         * @description One port's throughput over a trailing window, for a detail card.
         *
         *     Separate from `PortTraffic`, the overlay's sparse wire shape. This one is
         *     already attached to the port it describes, so it carries no identity and
         *     elides nothing -- an idle port on a card reads "0.00 Gbps" rather than
         *     vanishing the way it does from the overlay payload.
         */
        PortRate: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Rx */
            rx: number;
            /** Rxp */
            rxp: number;
            /** Span S */
            span_s: number;
            /** Tx */
            tx: number;
            /** Txp */
            txp: number;
        };
        /**
         * PortTraffic
         * @description One port's rate over the window.
         *
         *     Gbps on the wire rather than raw octets: the conversion needs `xmit_data`'s
         *     x4 scaling, the span, and the knowledge that these are wire bytes.
         *
         *     Sparse on a floor rather than on a flag, because traffic is genuinely dense
         *     where errors are not. An omitted port is below `IDLE_FLOOR_GBPS` and reads
         *     as idle either way.
         */
        PortTraffic: {
            /**
             * No Data
             * @default false
             */
            no_data: boolean;
            /** Node */
            node: string;
            /** Port */
            port: number;
            /**
             * Reset
             * @default false
             */
            reset: boolean;
            /**
             * Rx
             * @default 0
             */
            rx: number;
            /**
             * Rxp
             * @default 0
             */
            rxp: number;
            /**
             * Tx
             * @default 0
             */
            tx: number;
            /**
             * Txp
             * @default 0
             */
            txp: number;
        };
        /**
         * Rate
         * @description A speed or width, as stored and as read.
         */
        Rate: {
            /** Label */
            label?: string | null;
            /** Mask */
            mask?: number | null;
        };
        /**
         * Resolved
         * @description Which sweep answered this request. Present on every time-parameterised
         *     response.
         *
         *     Built from the `db.Resolved` dataclass the pool hands back.
         */
        Resolved: {
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Latest Sweep At */
            latest_sweep_at?: string | null;
            /** Latest Sweep Complete */
            latest_sweep_complete?: boolean | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Snapshot Id */
            snapshot_id: number;
            /** Topology Hash */
            topology_hash: string;
        };
        /** SnapshotRow */
        SnapshotRow: {
            /** Changed */
            changed: boolean;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Complete */
            complete: boolean;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Link Count */
            link_count: number;
            /** Node Count */
            node_count: number;
            /** Origin */
            origin: string;
            /** Port Count */
            port_count: number;
            /** Snapshot Id */
            snapshot_id: number;
            /** Source */
            source: string;
        };
        /**
         * Snapshots
         * @description Written unconditionally by the collector, so a gap in this
         *     list is a collector outage rather than a quiet fabric.
         */
        Snapshots: {
            /** Fabric */
            fabric: string;
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotRow"][];
        };
        /** SystemGroup */
        SystemGroup: {
            /** Children */
            children: string[];
            /** Label */
            label: string;
        };
        /** Topology */
        Topology: {
            counts: components["schemas"]["Counts"];
            /** Links */
            links: components["schemas"]["LinkElement"][];
            /** Nodes */
            nodes: components["schemas"]["NodeElement"][];
            resolved: components["schemas"]["Resolved"];
            /** System Groups */
            system_groups: {
                [key: string]: components["schemas"]["SystemGroup"];
            };
        };
        /**
         * TrafficCoverage
         * @description How much of the fabric the rate window saw.
         *
         *     Deliberately thinner than `CounterCoverage`: there is no `unsupported`,
         *     because PortXmitData and PortRcvData are mandatory in IBTA and no port
         *     fabricates them, and no `sweeps`, because a rate is bounded by two readings
         *     however many sat between them.
         */
        TrafficCoverage: {
            /** Ports Expected */
            ports_expected: number;
            /** Ports Measured */
            ports_measured: number;
            /** Ports No Data */
            ports_no_data: number;
            /** Ports Reset */
            ports_reset: number;
        };
        /** TrafficRates */
        TrafficRates: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Cadence S */
            cadence_s?: number | null;
            coverage: components["schemas"]["TrafficCoverage"];
            /** Fabric */
            fabric: string;
            /** First At */
            first_at?: string | null;
            /** Ports */
            ports: components["schemas"]["PortTraffic"][];
            /** Requested Window S */
            requested_window_s: number;
            /** Span S */
            span_s?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_fabrics_api_v1_fabrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FabricRow"][];
                };
            };
        };
    };
    errors_api_v1_fabrics__fabric__counters_errors_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                /** @description Seconds to look back before `since` for the baseline reading. 0 disables the asof baseline. */
                lookback?: number;
            };
            header?: never;
            path: {
                fabric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDeltas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traffic_api_v1_fabrics__fabric__counters_traffic_get: {
        parameters: {
            query?: {
                at?: string | null;
                /** @description Trailing window in seconds. Defaults to three times the fabric's observed traffic cadence. */
                window?: number | null;
            };
            header?: never;
            path: {
                fabric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficRates"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_api_v1_fabrics__fabric__diff_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
            };
            header?: never;
            path: {
                fabric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_fabrics__fabric__events_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                type?: string[] | null;
                limit?: number;
            };
            header?: never;
            path: {
                fabric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_api_v1_fabrics__fabric__head_get: {
        parameters: {
            query?: {
                at?: string | null;
            };
            header?: never;
            path: {
                fabric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Head"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_api_v1_fabrics__fabric__links__link_id__get: {
        parameters: {
            query?: {
                at?: string | null;
                /** @description Seconds of counter history to summarise on each port. Omit for no counters. Pass the same window the overlay is using, or the card and the graph will disagree. */
                counters_window?: number | null;
                /** @description Include per-port throughput. The window is server-sized from the fabric's observed traffic cadence, matching the overlay. */
                with_traffic?: boolean;
            };
            header?: never;
            path: {
                fabric: string;
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    node_api_v1_fabrics__fabric__nodes__guid__get: {
        parameters: {
            query?: {
                at?: string | null;
                /** @description Seconds of counter history to summarise on each port. Omit for no counters. Pass the same window the overlay is using, or the card and the graph will disagree. */
                counters_window?: number | null;
                /** @description Include per-port throughput. The window is server-sized from the fabric's observed traffic cadence, matching the overlay. */
                with_traffic?: boolean;
            };
            header?: never;
            path: {
                fabric: string;
                guid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_api_v1_fabrics__fabric__snapshots_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                fabric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshots"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topology_api_v1_fabrics__fabric__topology_get: {
        parameters: {
            query?: {
                at?: string | null;
            };
            header?: never;
            path: {
                fabric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topology"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
